fox-it/dissect.target

dissect/target/plugins/filesystem/resolver.py, dissect/target/plugins/os/windows/env.py, tests/conftest.py, tests/test_plugins_filesystem_resolver.py, tests/test_plugins_os_windows_env.py
The Windows path resolver now uses the paths defined in a target's %path% environment variable to try and resolve paths. Optionally a user's SID can be specified so the %path% variable for that specific user is used during resolving.
(DIS-801)
=> Use paths from %path% in Windows path resolver

dissect/target/filesystem.py, dissect/target/filesystems/ad1.py, dissect/target/filesystems/cb.py, dissect/target/filesystems/dir.py, dissect/target/filesystems/exfat.py, dissect/target/filesystems/extfs.py, dissect/target/filesystems/fat.py, dissect/target/filesystems/ffs.py, dissect/target/filesystems/ntfs.py, dissect/target/filesystems/vmfs.py, dissect/target/filesystems/xfs.py, dissect/target/helpers/fsutil.py, dissect/target/loaders/dir.py, dissect/target/loaders/vmcx.py, dissect/target/plugins/filesystem/resolver.py, dissect/target/plugins/os/windows/clfs.py, dissect/target/plugins/os/windows/iis.py, dissect/target/tools/shell.py, tests/conftest.py, tests/test_filesystem.py, tests/test_helpers_fsutil.py, tests/test_target_path.py
Path normalization is now done using the correct (alternative) path separators according to the path's source (filesystem).
TargetPath's flavours are now also set when not constructed through _from_parts().
(DIS-1639)
=> Adhere to the correct path separators

dissect/target/loaders/tar.py
File entries for legacy tar files (without an "fs/" path) now get the correct filesystem associated.
(DIS-1680)
=> Use the correct volume in the tar loader

setup.py
The reasons for this are three-fold:
- Basic acquire behaviour depends on the iis plugin, which requires defusedxml.
- The _os.py for esxi, which contains the basic esxi plugins, depends on it.
- Official Python documentation states that it is better to use defusedxml.etree.ElementTree when parsing XML from untrusted source then the build in ElementTree.
(DIS-1712)
=> Make defusedxml a main dependency

dissect/target/plugins/os/windows/thumbcache.py
=> Add `IndexRecord` to export thumbcache functions

dissect/target/plugin.py, dissect/target/plugins/apps/webservers/webservers.py, dissect/target/plugins/browsers/browser.py, dissect/target/plugins/general/plugins.py, dissect/target/plugins/os/windows/_os.py, dissect/target/plugins/os/windows/amcache.py, dissect/target/plugins/os/windows/generic.py, dissect/target/tools/query.py, dissect/target/tools/utils.py, tests/test_plugin.py
Features:
- Allow wildcards/fnmatch expression with -l/-f/-h
- If the output is mixed, ignore non-records and emit warning
- If -f/-l matches the root of the plugin tree then also execute based on tree
- Only allow exported functions with -l/-f/-h
- Only execute/show relevant functions with -f/-l if a target is provided
- Show functions supported by ANY of the specified targets
- Show loaders only if no target has been provided
- List generic OS functions under OS if no target has been specified
- Make -l work with multiple functions
- Batch mode: If multiple functions are requested, don't break on intermediate errors
- Allow child plugins to appear in plugin list as well (future)
- Allow quick and exceptionless compatibility checks (is_compatible)
- Allow plugins to "hide" from wildcard …
=> New implementation of -l/-f/-h

dissect/target/plugin.py
Execute entire namespace plugins like before.
(basically converts NS to MOD + * )
(DIS-1861)
=> Backward compatibility fix for plugin namespaces

dissect/target/tools/shell.py
This PR adds two features:
- add support for compressed files: use `fsutil.open_decompress` function for `cat` and `less` commands.
- enforce regular shell behaviour by defining an empty `emptyline` function in `TargetCmd`
=> Improve target-shell

dissect/target/plugins/os/unix/services.py, tests/data/plugins/os/unix/services/initd.sh, tests/data/plugins/os/unix/services/systemd.service, tests/data/plugins/os/unix/services/systemd2.service, tests/test_plugins_os_unix_services.py
This PR adds general improvements to the unix services plugin.
- adds support for initd services
- adds unit tests for systemd and initd services
- adds support for multi-line `ExecStart` commands in systemd service config files
=> Improve unix services plugin

dissect/target/plugins/os/unix/history.py, tests/conftest.py, tests/test_plugins_os_unix_history.py
This patch ensures all command history files on a target are parsed instead of only one.
=> Fix logic bug in unix history plugin

dissect/target/loader.py, dissect/target/loaders/cb.py, dissect/target/loaders/raw.py, dissect/target/target.py, tests/test_target.py
- Load all targets in dir instead of just one
- If it's a loadable dir, ignore non-targets
- Allows for multiple loadable dirs
- Suppress unnecessary errors
- For detailed description of behaviors see scenarios in unit tests (https://github.com/fox-it/dissect.target/pull/218/files#diff-bc9ab330a035ca1d92114c9b2cd7896e93e3def74e0ab9a6c22fa5bbeebcbb0dR23)
(DIS-1919)
Fixes https://github.com/fox-it/dissect.target/issues/215
=> Proposal processing directory target without wildcard

pyproject.toml, tests/test_plugins_apps_shell_powershell.py, tests/test_plugins_child_hyperv.py, tests/test_plugins_child_wsl.py, tests/test_plugins_os_windows_lnk.py
Some testcases are updated as record contents now contain the proper path separators.
(DIS-1848)
=> Update flow.record dependency to 3.10

dissect/target/plugin.py, dissect/target/plugins/general/osinfo.py, dissect/target/plugins/general/plugins.py, dissect/target/tools/query.py
- make plugin system compatible with plugins that require output files/dirs by checking output types early (None)
- allow users to get an OS summary in records by referencing the OS header in the -l output (-f OS)
=> Refine plugin system

dissect/target/plugins/os/windows/regf/appxdebugkeys.py, tests/test_plugins_os_windows_regf_appxdebugkeys.py
The idea behind this plugin is similar as for the runkeys plugin. AppX debug information registry keys can be used to gain persistency on a target.
(DIS-186)
=> Add a plugin to extract AppX debug information registry keys

dissect/target/filesystems/ntfs.py, tests/test_filesystems_ntfs.py
(DIS-2061)
Related: https://github.com/fox-it/dissect.ntfs/pull/21
=> Fix resolving invalid symlinks on NTFS

dissect/target/plugins/apps/av/mcafee.py
This fixes a minor issue in the McAfee plugin that wrongly suggests that the McAfee plugin is applicable to a certain target when it's not.
=> Fix false positive detection McAfee plugin

dissect/target/plugins/os/windows/defender.py, tests/test_plugins_os_windows_defender.py
This PR adds functionality to retrieve exclusions added to Windows Defender  from the 'Exclusions' registry key.
=> Add exclusions function to Windows Defender plugin

dissect/target/plugins/os/windows/adpolicy.py
- make the xml search query more generic so it also matches wrapped tasks
- make the plugin more robust (do not fail if appname is not present, happens sometimes)
=> Add support for gpo tasks that are wrapped in other tasks

dissect/target/plugins/os/unix/_os.py, tests/test_plugins_os_unix_version.py
When globbing for `/etc/*-release` it can encounter a directory, for example in Linux Mint:
`/etc/upstream-release/lsb-release`
This change ensures that we only parse files and not directories so it doesn't break parsing.
=> Skip directories in _parse_os_release

dissect/target/helpers/lazy.py
Sometimes an import might exist, but something that runs in the global scope of that import might break. Currently this would result in an infinite loop in the lazy importer. By catching all errors, the lazy import will be marked as failed regardless of error.
=> Make lazy import exception handler more broad

dissect/target/plugins/child/wsl.py, dissect/target/plugins/filesystem/resolver.py, tests/test_plugins_child_wsl.py, tests/test_plugins_filesystem_resolver.py
Updated wsl.py to not only look for WSL distribution disks (.vhdx) in default install location, but to use the Windows Registry of the Windows target to find other disk files for WSL on other locations as well which may not be on the default location.
=> Update WSL plugin to use registry to find all WSL instances

dissect/target/helpers/record.py
Constructors may not return anything except `None` as documented in `object.__init__`.
=> Remove return in constructor

dissect/target/plugins/child/wsl.py
#290 added WSL detection through the registry. This improvement however does not account for running `target-query --children` on non-Windows targets. This patch prevents the WSL child plugin from crashing when `self.target.registry` is not registered.
=> Fix child detection on Unix

dissect/target/helpers/mount.py
Fixes https://github.com/fox-it/dissect.target/issues/340
Because `.stat()` was used, the stat of the symlink/reparse point target was returned instead that of the file entry itself. This will make symlinks and reparse points correctly show up as symlinks.
One caveat, however, is that reparse points are always absolute. This means that they'll show up as this:
```bash
$ ls -lah /path/to/mnt/fs/sysvol
[...]
lrwxrwxrwx. 2 root root    0 Aug  1  2020 'Documents and Settings' -> /C:/Users
[...]
```
The same "problem" will occur with absolute symlinks.
A future improvement may want to dive into making these relative specifically within target-mount, but this seems to be a bit tough at the moment. Future improvements regarding sysvol on Windows may make this easier.
=> Use lstat instead of stat in target-mount

dissect/target/plugins/os/unix/bsd/citrix/_os.py
Fix a crash when fetching the timezone of the netscaler when it has a configline like 'set ns param -cookieversion 1 -timezone "GMT+02:00-CEST-Europe/Amsterdam"'.
```
Traceback (most recent call last):
File "/root/citrix-netscaler-triage/iocitrix.py", line 267, in <module>
main()
File "/root/citrix-netscaler-triage/iocitrix.py", line 263, in main
check_targets(args.targets)
File "/root/citrix-netscaler-triage/iocitrix.py", line 228, in check_targets
print_target_info(target)
File "/usr/local/lib/python3.9/dist-packages/dissect/target/tools/info.py", line 133, in print_target_info
print(f"Timezone      : {target.timezone}")
File "/usr/local/lib/python3.9/dist-packages/dissect/target/target.py", line 622, in __getattr__
result = func.__get__(p)
File …
```
=> Update Citrix _os.py for correct timezone detection

dissect/target/plugins/os/unix/linux/iptables.py, tests/test_plugins_os_unix_linux_iptables.py
This PR adds support for ufw to the iptables plugin.
=> Add support for ufw

dissect/target/plugins/os/windows/defender.py
This change adds support for quarantined regkeys and runkeys. It also fixes a bug for quarantined files without timestamps.
=> Create generic quarantine records for non-files

pyproject.toml, tests/test_plugins_apps_remoteaccess_anydesk.py, tests/test_plugins_apps_remoteaccess_teamviewer.py, tests/test_plugins_os_unix_log.py, tests/test_plugins_os_windows_tasks.py
The version specifier for flow.record is changed to include a third version part to prevent future breakage as flow.record versions with a different second version part are not necessary compatible.
(DIS-2209)
=> Update to flow.record 3.12

tests/test_loaders_remote.py
=> Improve remote loader test

dissect/target/plugins/os/unix/bsd/osx/user.py
Fixes test `test_plugins_os_windows_powershell` within `test_plugins_apps_shell_powershell` on Windows.
=> Make source field value a posix path

dissect/target/plugin.py, dissect/target/target.py, dissect/target/tools/query.py, tests/test_plugin.py, tests/test_tools_query.py
=> Fix logging of incompatible plugins

dissect/target/plugins/os/windows/task_helpers/tasks_xml.py, tests/test_plugins_os_windows_tasks.py
If Principals/Principal/DisplayName is empty, use the filename as the display_name.
I noticed that the field "Principals/Principal/DisplayName" is not used a lot, resulting in the Display Name being null for most of the records.
Instead, let's use the filename as Display Name (Like in the Task Scheduler GUI)
=> Get scheduled task display name with filename 

dissect/target/plugin.py, dissect/target/plugins/general/default.py
This allows for instance the log/file loader to access plugins even though the target does not have the necessary OS.
=> Allow DefaultOS to access all plugins

tests/test_plugins_os_unix_linux_modules.py
=> Fix an unstable ordering issue in the linux modules plugin test

dissect/target/tools/info.py
This PR aims to improve the stability of target-info when used on targets without optional `_os.py` functions.
=> Improve robustness of target-info

dissect/target/helpers/network_managers.py, dissect/target/plugins/apps/webservers/iis.py, dissect/target/plugins/child/wsl.py
=> Fix checks on non-existing or non-compatible plugins

tests/test_filesystems_config.py, tests/test_plugins_os_unix_linux_modules.py, tests/test_tools_shell.py
=> Skip failing tests on Windows for now

dissect/target/plugin.py, dissect/target/plugins/general/default.py, dissect/target/plugins/os/unix/_os.py, dissect/target/plugins/os/unix/bsd/osx/_os.py, tests/test_plugin.py, tests/test_plugins_general_default.py
This function is now mandatory to be implemented by all OSPlugin subclasses.
(DIS-2386)
=> Add the architecture function to OSPlugin

dissect/target/tools/query.py, tests/test_tools_query.py
=> Add an option to exclude functions from executing in target-query

dissect/target/tools/query.py, tests/test_tools_query.py
When using the option -n or --dry-run, target-query will show for each target which function would have been executed.
(DIS-2125)
=> Add a dry-run feature to target-query

dissect/target/plugins/os/windows/regf/runkeys.py
The "path" value of a run key is actually a full command. If this command does not have just a path but also things like command parameters, this can not be parsed as a path type.
The field is now treated as a normal string to prevent parse errors and in anticipation of a proper command field type.
(DIS-2563)
=> Change the RunKeyRecord path field to string

dissect/target/helpers/hashutil.py, dissect/target/plugins/filesystem/resolver.py, dissect/target/tools/query.py, tests/test_helpers_hashutil.py
=> Fix the hashutil functions to properly deal with path record field types

pyproject.toml
=> Update flow.record to 3.13

dissect/target/container.py, dissect/target/containers/asdf.py, dissect/target/containers/ewf.py, dissect/target/containers/hdd.py, dissect/target/containers/hds.py, dissect/target/containers/qcow2.py, dissect/target/containers/raw.py, dissect/target/containers/split.py, dissect/target/containers/vdi.py, dissect/target/containers/vhd.py, dissect/target/containers/vhdx.py, dissect/target/containers/vmdk.py, dissect/target/filesystem.py, dissect/target/volume.py, tests/data/plugin_register/container.py, tests/test_container_open.py, tests/test_filesystem.py, tests/test_volume.py
Fixes a bug that could happen due to https://github.com/fox-it/dissect.target/pull/403
=> Reset file position during container, volume and filesystem opening

MANIFEST.in, tests/conftest.py
The amount of test data is such that we fairly quickly run out of storage on pypi.org.
=> Do not package test data in the Python source distribution

dissect/target/plugins/browsers/browser.py, dissect/target/plugins/browsers/chrome.py, dissect/target/plugins/browsers/chromium.py, dissect/target/plugins/browsers/edge.py
In some cases the download URL isn't a valid link but a GUID `blob:null/<GUID>`, while the other tab URL related fields contain useful information about the origin of the downloaded file.
=> Add Tab URL's and MIME type to download record

dissect/target/plugins/os/unix/_os.py, dissect/target/plugins/os/unix/history.py, dissect/target/plugins/os/unix/linux/_os.py, tests/_data/plugins/os/unix/linux/alpine/_os/alpine-os-release, tests/plugins/os/unix/test_version.py
This PR adds improved support for os version detection on alpine linux systems.
=> Improve support for alpine linux

dissect/target/target.py, dissect/target/volume.py, dissect/target/volumes/bde.py, dissect/target/volumes/ddf.py, dissect/target/volumes/disk.py, dissect/target/volumes/luks.py, dissect/target/volumes/lvm.py, dissect/target/volumes/md.py, dissect/target/volumes/vmfs.py, tests/test_target.py, tests/volumes/test_bde.py
As part of this fix I've introduced a `__type__` attribute to the `VolumeSystem` class. It's purpose is similar to `Filesystem.__fstype__` - being able to do some sort of type-check if you can't do a `isinstance()` check due to lazy importing.
In fact, I probably want to add it to `Container` too, and perhaps rename `Filesystem.__fstype__` to `Filesystem.__type__` - of course with the necessary deprecation warning and period.
=> Fix handling of volumes at offset 0

dissect/target/plugins/apps/av/symantec.py
Fix Symantec compatibility check.
Glob returns a generator which equals to True, even if empty. Also break doesn't work that way.
=> Fix Symantec compatibility check

dissect/target/plugins/os/windows/lnk.py
=> Add _target to LnkRecord

dissect/target/plugins/apps/remoteaccess/teamviewer.py, tests/_data/plugins/apps/remoteaccess/teamviewer/TestTeamviewer.log, tests/plugins/apps/remoteaccess/test_teamviewer.py
=> Fix multiple datetime parsing issues in teamviewer plugin

dissect/target/loaders/targetd.py, dissect/target/plugin.py
=> Fix issues with targetd integration

tests/conftest.py, tests/filesystems/test_config.py, tests/filesystems/test_dir.py, tests/helpers/test_fsutil.py, tests/plugins/apps/browser/test_browser.py, tests/plugins/filesystem/test_yara.py, tests/plugins/os/unix/test__os.py, tests/test_filesystem.py, tests/tools/test_dump.py, tests/tools/test_shell.py
On Windows, files can not be opened when already open. This gives issues when using temporary files. By not deleting a temporaryfile after it is closed and closing it after it is created, this is circumvented.
By moving all these files into pytest's tmp_path, the tmp_path mechanism will take care of removing these temporary files.
=> Fix permission issues when tests are run on windows

dissect/target/filesystems/extfs.py, dissect/target/plugins/filesystem/walkfs.py
The walkfs plugin would always report btime=None, which is a shame since ext4 does support birth timestamps (called crtime in ext lingo).
dissect.extfs already supported crtime, so a simple fix suffices.
=> Add support for birth timestamps in extfs / walkfs

dissect/target/plugins/os/windows/regf/mru.py
An MRU key does not always have a `MRUList` key/value pair. This assumption is now fixed.
=> Fix MRUList assumption

dissect/target/plugins/os/windows/cim.py
A consumer binding can exist without the `CommandLineTemplate` property. This assumption is now fixed by checking for this property before accessing it's value.
=> Fix consumerbindings plugin

dissect/target/plugins/os/unix/generic.py, dissect/target/tools/info.py
When a target system contains (broken) symlinks in `/var/log, the activity plugin could break. This is now fixed by checking if a file is a symlink or if it exists at all.
=> Fix unix activity plugin

dissect/target/plugin.py
=> Fix finding namespace plugins that do not want to be __findable__

dissect/target/plugins/apps/vpn/openvpn.py
Resolved an issue in the OpenVPNPlugin where the 'client-to-client' configuration option was incorrectly processed. Previously, the code attempted to use the value directly from the configuration, which led to errors when this value was an empty string. This fix ensures that an empty string for 'client-to-client' defaults to False, aligning with the expected boolean behavior of this configuration parameter.
=> Fix boolean parsing in OpenVPNPlugin

dissect/target/loaders/asdf.py, dissect/target/loaders/log.py, dissect/target/loaders/raw.py, dissect/target/loaders/remote.py, dissect/target/loaders/targetd.py, dissect/target/loaders/vmwarevm.py, dissect/target/plugins/general/loaders.py, dissect/target/tools/query.py, dissect/target/tools/utils.py, tests/loaders/test_log.py, tests/tools/test_utils.py
=> Explicit loader Option

dissect/target/plugins/os/windows/tasks.py
This fixes fox-it/flow.record#99 when used with rdump --multi-timestamp
=> Remove duplicate field in TaskRecord

tests/plugins/os/unix/linux/redhat/test_yum.py
It previously relied on the modified timestamp of the test file, but fresh checkouts will now have a modification time in 2024. This fix mocks the modified timestamp to be in 2023.
=> Fix yum year rollover unit test

dissect/target/helpers/fsutil.py, tests/helpers/test_fsutil.py
When passed a pattern with path parts which did not contain any globs, the function would fail due to path strings instead of FilesystemEntry's being used.
Documentation and comments are added to the glob_ext*() functions and they are refactored a bit.
(DIS-2903)
=> Fix the glob_ext() filesystem globbing function

dissect/target/filesystem.py, dissect/target/helpers/compat/path_310.py, dissect/target/helpers/compat/path_311.py, dissect/target/helpers/compat/path_312.py, dissect/target/helpers/compat/path_39.py, dissect/target/helpers/compat/path_common.py, dissect/target/helpers/fsutil.py, dissect/target/helpers/polypath.py, pyproject.toml, tests/conftest.py, tests/helpers/test_fsutil.py, tests/test_filesystem.py, tests/tools/test_utils.py
This refactors TargetPath into a structure that's hopefully a little easier to maintain for future Python versions. TargetPath implementations are now split into different files, one for each Python version. Each file has specific changes needed to make it work. Each new release of Python still requires a new patch though.
I've also fixed some small filesystem and other test related bugs I ran into to get this all working.
As I'm writing this, I'm also starting to wonder at what point it might be a better idea to just... subclass `pathlib.Path` but literally override everything. I'm sure that has it's own set of challenges though.
Depends on https://github.com/fox-it/flow.record/pull/91
=> Refactor TargetPath and add support for Python 3.12

dissect/target/containers/ewf.py
The EWF implementation in `dissect.evidence` does LRU, but that requires passing in the `Path` objects instead of file-like objects. The current code just tries to open _all_ the files at once. Passing the `Path` objects instead will allow us to properly utilize the internal LRU.
=> Fix file handle exhaustion for EWF files with many chunks

.gitattributes, dissect/target/loaders/tar.py, tests/_data/loaders/tar/test-anon-filesystems.tar, tests/loaders/test_tar.py
=> Fix loading of anonymous filesystems in the TarLoader

dissect/target/plugins/filesystem/ntfs/mft.py, dissect/target/plugins/filesystem/ntfs/mft_timeline.py, dissect/target/plugins/filesystem/ntfs/usnjrnl.py, dissect/target/plugins/filesystem/ntfs/utils.py, tests/plugins/filesystem/ntfs/test_mft.py
As of c97c344 filesystems are always mounted. In the case of "fake" NTFS filesystems, as used by e.g. the dir and tar loaders, this means such a filesystem can be present under up to three different mount points, e.g.: sysvol, C: and $fs$\fs0
When a plugin does not use the root filesystem but the bare ntfs filesystem to parse ntfs specific properties, e.g. the mft plugin, it extends paths with a "driveletter" (read: mountpoint) to construct a path that is reachable from the root filesystem.
The old setup always returned the last mount point a drive was mounted under. The new setup changes this to return the first mount point present in the following order:
1. the first mount point with a letter and colon, e.g. C:,
2. the first mount point not starting with $fs$, e.g. sysvol,
3. the first …
=> Improve driveletter selection for windows disks

dissect/target/helpers/keychain.py, dissect/target/volumes/bde.py, dissect/target/volumes/luks.py, tests/helpers/test_keychain.py
Also strip quotes from recovery key and file values, in case those were added with a quote for e.g. spaces in them.
=> Reduce log verbosity of wildcard keychain values

dissect/target/plugins/os/unix/linux/fortios/_os.py, dissect/target/plugins/os/unix/linux/fortios/generic.py, dissect/target/plugins/os/unix/linux/fortios/locale.py
This PR adds rudimentary support for decrypting `rootfs.gz` files on FortiOS 7.4.1 and up.
=> Add FortiOS rootfs.gz decrypt functionality

tox.ini
Some tests seem to be dependent on the order they are executed and will fail with pytest 8.0.0's new test collection order.
(DIS-2970)
=> Pin pytest to a version <8.0.0 for now

dissect/target/plugins/os/unix/_os.py, tests/plugins/os/unix/test__os.py
Wrote as fix for ticket DIS-2796, where the hostname could not be found for Red Hat systems. The hostname for these files is instead of /etc/hostname found within /etc/sysconfig/network.
=> Fix hostname plugin for RedHat systems

dissect/target/plugins/apps/browser/iexplore.py, tests/plugins/apps/browser/test_iexplore.py
=> Fix iexplore download records to use a proper path

dissect/target/plugin.py
The copy made of the global plugin list was to shallow, resulting in the get_all_records() exports being removed from the list of exports.
DIS-2971
=> Fix removing get_all_records() exports by plugin_function_index()

dissect/target/plugins/apps/browser/browser.py, dissect/target/plugins/apps/browser/chrome.py, dissect/target/plugins/apps/browser/chromium.py, dissect/target/plugins/apps/browser/edge.py, dissect/target/plugins/apps/browser/firefox.py
Mostly moving around of some functions, and adding a source field to the cookies record.
=> Small consistency fixes in browser plugins

tests/loaders/test_cb.py, tests/plugins/os/windows/test_registry.py, tests/test_plugin.py, tests/test_target.py
These are due to the tests (inadvertently) changing global state.
(DIS-2971)
=> Fix some issues with tests not being independent from other tests

dissect/target/plugins/apps/webserver/apache.py, tests/plugins/apps/webserver/test_apache.py
This PR adds two paths to the ApachePlugin to account for installations of XAMPP on Windows and / or Linux.
=> Add xampp paths to ApachePlugin

dissect/target/plugins/apps/browser/brave.py, dissect/target/plugins/apps/browser/chromium.py, tests/plugins/apps/browser/test_brave.py
This PR adds a `BrowserPlugin` for Brave. 
While working on this PR we found that cookies are stored in the `Network` subfolder in newer versions of Chromium-based browsers.  We therefore made a small addition to `_iter_db` to support checking additional subfolders, which can then be used in the `cookies` method.
=> Add Brave browser plugin

dissect/target/plugins/os/unix/locate/plocate.py
Apply the workaround to the whole of PyPy instead of just PyPy 3.9. Since it seems to affect PyPy 3.10 as well.
=> Apply bug workaround in plocate plugin to all PyPy versions

pyproject.toml
Yara-python now provides their own pre-compiled wheels, so revert back to the official dependency
=> Revert back to yara-python

dissect/target/filesystems/tar.py
Turns out that `tarfile.is_tarfile()` will read entire files (or partitions/disks, in our case...) to check if something is a tar file.
=> Fix performance regression due to TarFilesystem

tests/test_filesystem.py
=> add tests for symlink logic MappedFile

dissect/target/loaders/dir.py, dissect/target/loaders/velociraptor.py, tests/loaders/test_kape.py, tests/loaders/test_tanium.py, tests/loaders/test_velociraptor.py
Fixes https://github.com/fox-it/dissect.target/issues/557
@Zawadidone can you confirm whether my assumption with regards to the drive letter directory name is correct?
=> Mount volumes to drive letters in Velociraptor loader

dissect/target/plugins/os/unix/linux/services.py
Previously discussed in issues.
Having a service installed on an image, that has a hyphen in the key makes target.services() raises a RecordDescriptorError exception.
By adding a simple replace of the hyphen to underscore, it runs without issues.
=> Replaced hyphen in key

dissect/target/helpers/network_managers.py
=> Fix log message calls in network manager

dissect/target/plugins/os/windows/_os.py
=> Fallback mount sysvol to C: if not mounted to another drive letter

dissect/target/plugins/apps/browser/iexplore.py
This PR fixes an error in the `iexplore.downloads` function.
When `container_record.ResponseHeaders` does not exist or fails to be decoded, the variable `down_path` stays set to `None`. When passing `None` to `self.target.fs.path` / `TargetPath` we get an ugly exception.
This is fixed by properly checking if `down_path` is truthy before calling `self.target.fs.path`.
=> Fix TypeError in iexplore.downloads `down_path`

dissect/target/loaders/mqtt.py, dissect/target/tools/query.py, tests/loaders/test_mqtt.py
=> Add prefetch to MQTT loader

dissect/target/plugins/apps/browser/firefox.py, tests/_data/plugins/apps/browser/firefox/extensions.json, tests/plugins/apps/browser/test_firefox.py
This PR adds the capability to parse firefox extensions (at least for Firefox 26+) to the firefox browser plugin. 
```
target-query -f firefox.extensions TARGET | rdump -L 
[reading from stdin]
[...]
--[ RECORD 12 ]--
hostname = WINDOWS11
domain = None
ts_install = 2024-04-23 08:03:15+00:00
ts_update = 2024-04-23 08:03:15+00:00
browser = firefox
id = wappalyzer@crunchlabz.com
name = Wappalyzer - Technology profiler
short_name = None
default_title = None
description = Identify web technologies
version = 6.10.68
ext_path = C:\Users\Win11\AppData\Roaming\Mozilla\Firefox\Profiles\9nxit8q0.default-release\extensions\wappalyzer@crunchlabz.com.xpi
from_webstore = None
permissions = ['cookies', 'storage', 'tabs', 'webRequest']
manifest_version = 2
source = …
```
=> Add firefox extensions within firefox plugin

dissect/target/exceptions.py, dissect/target/loaders/raw.py, dissect/target/target.py
=> Return descriptive error when target tools point to a non-existing file

dissect/target/plugins/os/unix/locate/plocate.py, tests/plugins/os/unix/locate/test_plocate.py
(DIS-3233) Attempts to fix #696
=> Fix path parsing bug in plocate

dissect/target/tools/shell.py
=> Add generic error handler and debug mode

dissect/target/loaders/mqtt.py, tests/loaders/test_mqtt.py
=> Add monitoring option to MQTT Loader

dissect/target/filesystem.py, dissect/target/helpers/hashutil.py, tests/helpers/test_hashutil.py
=> Remove deprecated features marked for removal in version 3.15

dissect/target/plugins/os/unix/etc/etc.py
=> Add glob/dump function for config tree

dissect/target/plugins/os/unix/history.py, tests/plugins/os/unix/test_history.py
In the edge case where the path of a unix history file is a directory, the unix history plugin fails as it only checks the path exists and, if so, assumes it is a file. This PR fixes this problem by explicitly checking the path is a file.
=> Fix edge case where unix history path is a directory

dissect/target/loaders/mqtt.py, tests/loaders/test_mqtt.py
=> Add username and password options to MQTT loader

dissect/target/plugins/os/unix/_os.py, dissect/target/plugins/os/unix/shadow.py, tests/plugins/os/unix/test_shadow.py, tests/plugins/os/unix/test_users.py
This PR adds support for the `/etc/passwd-` and `/etc/shadow-` backup files.
=> Add support for passwd backup files

dissect/target/plugins/os/windows/_os.py
=> Fix wrong log logic indicating a sysvol was not found

dissect/target/plugins/apps/browser/chromium.py, dissect/target/plugins/apps/browser/firefox.py
The browser.cookies plugin returned records without target information for Firefox and Chromium browsers.
=> Add _target field to firefox and chromium  plugins

dissect/target/plugins/os/windows/regf/usb.py, tests/plugins/os/windows/regf/test_usb.py
This PR rewrites the existing Windows USB plugin and adds a test based on a Windows 10 22H2 system.
=> Rewrite Windows USB plugin

dissect/target/plugins/filesystem/yara.py, dissect/target/target.py, dissect/target/tools/yara.py
This is a small improvement on #646 that adds `--children` to `target-yara` / `target-query -f yara`.
=> Add option to scan children in YARA plugin

dissect/target/plugins/apps/browser/firefox.py, dissect/target/plugins/general/users.py, tests/_data/plugins/apps/browser/firefox/android/org.mozilla.vrbrowser/files/mozilla/act660uy.default/cookies.sqlite, tests/_data/plugins/apps/browser/firefox/android/org.mozilla.vrbrowser/files/mozilla/act660uy.default/extensions.json, tests/_data/plugins/apps/browser/firefox/android/org.mozilla.vrbrowser/files/mozilla/profiles.ini, tests/_data/plugins/apps/browser/firefox/android/org.mozilla.vrbrowser/files/places.sqlite, tests/plugins/apps/browser/test_firefox.py
Depends on and separated from https://github.com/fox-it/dissect.target/pull/419
=> Add support for Firefox Oculus VR browser

dissect/target/plugins/os/unix/esxi/_os.py
When the hypervisor is not fully installed yet, the local state file may not exist yet.
=> Fix ESXi OS when no local state exists yet

dissect/target/helpers/config.py, dissect/target/target.py, dissect/target/tools/shell.py
This PR adds support for target-shell history files to dissect as described in #650.
Small changes were made to the config helper utility to also scan the current working directory for `.targetcfg.py` files. The storage location of the shell history by default is `$HOME/.dissect_history` and can be changed with the `HISTFILE` variable in `.targetcfg.py`.
=> Add target-shell history

dissect/target/filesystems/zip.py, tests/filesystems/test_zip.py
This might fix #699 (@Zawadidone could you confirm?) and probably makes #793 redundant (sorry 😅).
This also reworks the internals of the `ZipFilesystem` a little bit.
=> Add symlink support to ZipFilesystem

dissect/target/helpers/fsutil.py
=> Add st_birthtime_ns to fsutil.stat_result

dissect/target/tools/shell.py
=> Add notice for PyPy users 

dissect/target/plugins/filesystem/ntfs/mft.py, dissect/target/tools/utils.py, tests/tools/test_utils.py
=> Add mutual exclusive plugin arguments

dissect/target/plugins/os/windows/adpolicy.py, dissect/target/plugins/os/windows/regf/shimcache.py, dissect/target/plugins/os/windows/task_helpers/tasks_xml.py, dissect/target/tools/query.py, tests/plugins/apps/ssh/test_putty.py, tests/plugins/os/unix/test_generic.py
This PR, together with https://github.com/fox-it/flow.record/pull/136 should fix all pytest deprecation warnings when running CPython 3.12.
=> Fix 3.12 ET and datetime deprecation warnings

pyproject.toml
=> Bump the version of flow.record to 3.16

dissect/target/loaders/mqtt.py
This is a companion PR of the agent and cannot be tested stand-alone.
To test together with the agent,
1. Generate an agent
2. Deploy it on a machine.
3. Start the broker
4. Run the command below
```
target-query all -L mqtt --mqtt-port=443 --mqtt-broker=0.0.0.0 --mqtt-ca=domain.crt --mqtt-crt=/tmp/cert.crt --mqtt-key=/tmp/private.key --mqtt-case=case1 --mqtt-peers=100 --mqtt-username=ag_case1_roel --mqtt-password --mqtt-diag --mqtt-command callid  -f hostname
```
closes #846
=> Dis 3281/improved security scheme

dissect/target/plugins/os/windows/defender.py
It is what it says in the title. The defender.exclusion plugin was missing the _target field which causes the hostname etc. to be None.
=> [Bug] Add missing _target field to record for Defender exclusion plugin

dissect/target/plugins/os/unix/log/messages.py
This PR improves the cloud-init log line regex from the `messages` plugin.
=> Make cloud-init log line regex more strict

dissect/target/plugins/os/unix/bsd/osx/_os.py, tests/plugins/os/unix/bsd/osx/test__os.py
This fixes an issue where the home directory could not be found when running dissect on windows.
@pyrco also helped 
Closes #866
=> Mark OSX home directory as a posix path

dissect/target/plugins/filesystem/ntfs/mft.py, tests/plugins/filesystem/ntfs/test_mft.py
Avoids hiding several ADS MACBs behind the same TS.
=> Unfold ADS macb records

dissect/target/tools/shell.py, tests/tools/test_shell.py
=> Add support for runtime aliases to target_shell

dissect/target/tools/shell.py, tests/tools/test_shell.py
Support execution of a `~/.targetrc` file when a target shell is opened, and `~/.targetrc.registry` in case of the registry shell.
We have decided on separate run command files because the registry and target shell are not compatible.
Additionally:
- The run commands files to be executed can be configured per-target by setting the `TARGETRCFILE` (and `TARGETRCFILE_REGISTRY`)  variables inside the target configuration file.
Closes #592
=> Add support for targetrc file to execute commands when a target shell is spawned

dissect/target/tools/shell.py, tests/tools/test_shell.py
=> Add -c argument to target_shell

dissect/target/plugins/os/unix/_os.py, dissect/target/plugins/os/windows/_os.py, tests/plugins/os/unix/bsd/citrix/test__os.py, tests/plugins/os/unix/bsd/osx/test__os.py, tests/plugins/os/unix/linux/test_environ.py, tests/plugins/os/unix/test__os.py, tests/plugins/os/windows/test__os.py
- Explicitly mark home directories as either `posix_path` or `windows_path`
- Add missing unit test for parsing of users on windows and unix
Closes #891
=> Explicitly mark home directories as having a posix or windows flavor

dissect/target/filesystems/config.py, dissect/target/helpers/configutil.py, tests/helpers/test_configutil.py
=> Add binary configuration parser 

dissect/target/helpers/configutil.py, dissect/target/plugins/apps/other/env.py, tests/_data/helpers/configutil/env, tests/_data/plugins/apps/other/env/test.env, tests/helpers/test_configutil.py, tests/plugins/apps/other/test_envfile.py
This PR adds an environment file parser to the ConfigurationParser helper utility. Fixes #888.
=> Add Env ConfigurationParser

dissect/target/tools/shell.py
#873 has broken the `python` shell command in `target-shell`. This PR should fix that.
=> Fix broken python command in target-shell

dissect/target/plugins/os/unix/log/auth.py, tests/_data/plugins/os/unix/log/auth/iso.log, tests/plugins/os/unix/log/test_auth.py
This PR builds on top of #860 and introduces support for ISO 8601 formatted timestamps in `auth.log` files which can (finally :partying_face:) be found in newer Debian and Ubuntu systems. Fixes #903.
=> Add support for ISO 8601 formatted auth log timestamps

dissect/target/filesystems/jffs.py, tests/filesystems/test_jffs2.py, tests/filesystems/test_xfs.py
The block size  is a function of the "erase size" of the underlying flash device.
Linux stat reports the default block size, which is defined as 4k in libc. 
Note that JFFS2 does not support non-residential symlinks (see https://github.com/torvalds/linux/blob/6485cf5ea253d40d507cd71253c9568c5470cd27/fs/jffs2/dir.c#L299)
Closes #819
=> Support st_blksize and st_blocks on JFFS2

dissect/target/filesystems/ffs.py, tests/filesystems/test_ffs.py
On Linux, stat always returns the default block size of 4096
We are returning the actual block size of the filesystem, similar to stat on  BSD
Note: st_blocks * 512 can be lower than st_blksize because FFS employs fragments
Closes #818
=> Add blksize, nblocks, and birthtime_ns to stat for FFS

dissect/target/plugins/os/unix/log/auth.py, tests/_data/plugins/os/unix/log/auth/iso.log, tests/plugins/os/unix/log/test_auth.py
=> Refactor AuthLogPlugin

dissect/target/container.py, dissect/target/exceptions.py, dissect/target/filesystem.py, dissect/target/filesystems/btrfs.py, dissect/target/filesystems/extfs.py, dissect/target/filesystems/fat.py, dissect/target/filesystems/ffs.py, dissect/target/filesystems/jffs.py, dissect/target/filesystems/ntfs.py, dissect/target/filesystems/smb.py, dissect/target/filesystems/squashfs.py, dissect/target/filesystems/vmfs.py, dissect/target/filesystems/xfs.py, dissect/target/helpers/regutil.py, dissect/target/plugin.py, dissect/target/target.py, dissect/target/tools/utils.py, dissect/target/volume.py
=> Remove Python 2 compatible exception code

dissect/target/plugins/os/windows/syscache.py, tests/_data/plugins/os/windows/syscache/Syscache-mft.hve, tests/plugins/os/windows/test_syscache.py
``dissect.ntfs`` changes probably caused regression in syscache plugin that now raises following ``AttributeError`` for me:
```
$ target-query -q -f syscache  DC1.tar
Traceback (most recent call last):
File "/home/user/test-venv/bin/target-query", line 8, in <module>
sys.exit(main())
File "/home/user/test-venv/lib/python3.9/site-packages/dissect/target/tools/utils.py", line 276, in wrapper
return func(*args, **kwargs)
File "/home/user/test-venv/lib/python3.9/site-packages/dissect/target/tools/query.py", line 384, in main
raise e
File "/home/user/test-venv/lib/python3.9/site-packages/dissect/target/tools/query.py", line 373, in main
for record_entries in entry:
File "/home/user/test-venv/lib/python3.9/site-packages/dissect/target/plugins/os/windows/syscache.py", line 78, in syscache …
```
=> Fix AttributeError in syscache plugin

dissect/target/helpers/configutil.py, dissect/target/helpers/record.py, dissect/target/helpers/utils.py, dissect/target/plugins/general/network.py, dissect/target/plugins/os/unix/bsd/osx/network.py, dissect/target/plugins/os/unix/linux/_os.py, dissect/target/plugins/os/unix/linux/network.py, dissect/target/plugins/os/windows/network.py, tests/_data/plugins/os/unix/linux/NetworkManager/vlan.nmconnection, tests/_data/plugins/os/unix/linux/NetworkManager/vlan2.nmconnection, tests/_data/plugins/os/unix/linux/NetworkManager/wired-static.nmconnection, tests/_data/plugins/os/unix/linux/NetworkManager/wireless.nmconnection, tests/_data/plugins/os/unix/linux/systemd.network/20-vlan.netdev, tests/_data/plugins/os/unix/linux/systemd.network/20-vlan2.netdev, tests/_data/plugins/os/unix/linux/systemd.network/20-wired-static.network, tests/_data/plugins/os/unix/linux/systemd.network/30-wired-static-complex.network, tests/_data/plugins/os/unix/linux/systemd.network/40-wireless-ipv4.network, tests/_data/plugins/os/unix/linux/systemd.network/40-wireless-ipv6.network, tests/_data/plugins/os/unix/linux/systemd.network/40-wireless.network, tests/helpers/test_utils.py, tests/plugins/general/test_network.py, tests/plugins/os/unix/bsd/osx/test_network.py, tests/plugins/os/unix/linux/test_network.py, tests/plugins/os/windows/test_network.py
Implement the `NetworkPlugin` for Linux.
Initial support is for:
- NetworkManager
- systemd-networkd
~~The `ips` method of the Linux OS plugin is implemented using the new parser; other methods such as `dns` and `dhcp` still use the legacy solution until we implemented parsers for the remaining network configuration systems. Let me know if this is wrong.~~ 
Update: I retained the old `ips`. The new implementation can be invoked by prefixing with the `network` namespace, i.e. `-f network.interfaces`
While doing research I discovered  that systemd supports "drop-in"  configuration directories (see https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html) . Since this feature applicable to all systemd domains and not only networking, I propose we extend the systemd config …
=> Linux network plugin: NetworkManager & systemd-networkd

dissect/target/helpers/regutil.py, tests/helpers/test_regutil.py
This PR fixes edge cases where `RegfValue.type` cannot be translated to the `RegistryValueType` enum.
=> Allow RegfValue.type to fall back to int

dissect/target/plugins/os/windows/network.py, tests/plugins/os/windows/test_network.py
=> Fix error in windows network plugins

dissect/target/plugins/os/windows/regf/cit.py
This PR aims to improve the robustness of the Windows CIT plugin by catching EOFError exceptions.
=> Improve cit plugin exception handling

pyproject.toml, tests/loaders/test_mqtt.py
We remove an import at the top, but now have to import the unit under test in the test itself.
Closes #926
=> Remove paho from mqqt unit test

dissect/target/plugins/os/windows/log/mssql.py
=> Make Mssql errorlog plugin more robust

dissect/target/plugins/os/windows/task_helpers/tasks_xml.py, dissect/target/plugins/os/windows/tasks.py, tests/_data/plugins/os/windows/tasks/InvalidTask, tests/plugins/os/windows/test_tasks.py
=> Continue parsing tasks after invalid Windows XML Task

dissect/target/helpers/fsutil.py, tests/helpers/test_fsutil.py
Previously file header could be misread if fileobj position was not at start, leading to incorrect file format detection. Now explicitly seek to beginning before reading the magic file header bytes.
Also fixed the example in the docstring of `open_decompress` so that it renders it as a code block.
fixes #999
=> Fix file header detection in open_decompress

dissect/target/helpers/regutil.py, dissect/target/helpers/utils.py, dissect/target/loaders/cb.py, dissect/target/loaders/smb.py, dissect/target/plugins/apps/productivity/msoffice.py, dissect/target/plugins/filesystem/resolver.py, dissect/target/plugins/os/unix/linux/network.py, dissect/target/plugins/os/windows/registry.py, tests/_data/plugins/apps/productivity/vsto/MicrosoftDataStreamerforExcel.dll.manifest, tests/_data/plugins/apps/productivity/vsto/MicrosoftDataStreamerforExcel.vsto, tests/_data/plugins/apps/productivity/wef/Manifests/wa200007708_1.0.0.0, tests/helpers/test_utils.py, tests/plugins/apps/productivity/test_msoffice.py, tests/plugins/filesystem/test_resolver.py
Detects:
- Persistence through startup folders (templates, executables)
- COM addins 
- VSTO addins by parsing ClickOnce Deployment manifests
- Web addins by inspecting WEF cache and parsing manifests
Limitations:
- Office for Mac is not supported
- Supports Microsoft Office 2016 and later
- Manifests which are wof compressed are unreadable
Bonus:
- Fix issue in resolver where user environment was not taken into account when expanding paths
- Fix issue where partial path resolution resolved to directories.
- Added convenience functions for querying registry
=> Microsoft Office add-in detection 

dissect/target/helpers/fsutil.py, dissect/target/tools/diff.py, tests/helpers/test_fsutil.py, tests/tools/test_diff.py
This PR addresses the following in `target-diff`:
1. We now read changed files (in deep mode) in reverse instead of from the beginning. We could add a feature flag for this if desired, e.g. `--read-mode`. We feel reverse should be the default since most files are appended instead of prepended.
2. The `--exclude` parameter did not function as one would expect, this is now changed.
=> Improve target-diff tool

dissect/target/plugins/os/unix/_os.py, dissect/target/plugins/os/unix/linux/_os.py
This PR aims to improve the detection of Linux-like filesystems in dissect.
On a side note, certain functionality in the `unix` space is actually `linux` specific (e.g. user parsing, fstab parsing, hostname parsing). Fixing this disambiguation and mixed shared functionality between `unix` and `linux` OS plugins is something for another time perhaps.
=> Improve Linux detection

dissect/target/plugin.py, tests/test_plugin.py
General idea is that you create your plugin in a file called `_plugin.py` in a certain directory. That directory can then hold other files such as specific helpers. The plugin path/name is then derived from the directory path up until the module name, instead of including it.
For example:
```
apps/something/myapp
- _plugin.py
- helpers.py
```
The plugin will register under the `apps.something.myapp` path.
Closes https://github.com/fox-it/dissect.target/issues/890.
=> Add support for plugin directories

dissect/target/plugins/os/unix/log/helpers.py, dissect/target/plugins/os/unix/log/messages.py, tests/plugins/os/unix/log/test_messages.py
Some Linux systems can include kernel ring buffer log messages in their syslogs. This PR adds support for those log lines.
=> Add support for kernel log entries in syslog

dissect/target/plugin.py, tests/test_plugin.py
This PR fixes the `find_plugins` function with `compatibility=True`. Previously descriptors were yielded if they were not seen before, regardless of their compatibility.
=> Fix compatible plugins filter

dissect/target/plugin.py, tests/test_plugin.py
This PR fixes the `find_plugins` function with `compatibility=True` for plugin classes with multiple exported functions. Previously only the first descriptor was yielded and any other descriptors of the same plugin class were ignored.
This solution introduces a slightly slower `_filter_compatible` function. We could also keep `seen: set[Plugin]` and iterate over `plugincls.__functions__` once the plugin is determined to be compatible, but that might not work as intended for namespace plugins and regular plugins with multiple function exports.
=> Fix compatible plugins filter (2)

dissect/target/filesystems/jffs.py, pyproject.toml, tests/filesystems/test_jffs2.py
Companion to https://github.com/fox-it/dissect.jffs/pull/13/files
=> feature: add nlink support for jffs stat

dissect/target/plugins/apps/chat/chat.py, dissect/target/plugins/apps/chat/msn.py, dissect/target/plugins/os/windows/_os.py, tests/_data/plugins/apps/chat/msn/history.xml, tests/plugins/apps/chat/test_msn.py, tests/plugins/os/windows/test__os.py
This PR adds support to dissect for the Windows Live Messenger application. Currently works on `WLM 2009` and `MSN 7.5` (on Windows 7 and XP), other versions might work too but have not been tested. Artifacts from `Messenger Plus! Live` are currently not supported.
=> Add Windows MSN plugin

tests/conftest.py, tests/test_plugin.py, tests/tools/test_query.py
After we enabled test randomization, sometimes we get a test failure on`tests/tools/test_query.py::test_invalid_functions` and `tests/tools/test_query.py::test_invalid_excluded_functions` (https://github.com/fox-it/dissect.target/actions/runs/14494203513/job/40657657729?pr=1108)
However, I can't reproduce even with the same seed. I have a suspicion that a cached `_generate_long_paths` is the issue, so I moved the clearing of that cache from just the `test_plugin.py` file to every test in the suite.
=> Clear cached functions on every test

dissect/target/plugins/os/windows/defender/quarantine.py, tests/plugins/os/windows/test_defender.py
This PR adds the handling of the other valid stream IDs as described by https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-bkup/71b49aa4-1f4f-4e1b-84a4-56f560002cf6 for the Dissect Windows Defender quarantine implementation. Now all valid values are caught and invalid values should raise an exception. I couldn't find any test cases already, so I didn't add/alter test cases.
Resolves #1107.
=> Add other Windows Defender quarantine file stream IDs

dissect/target/plugins/os/unix/_os.py, tests/plugins/os/unix/test__os.py
In succession of #1079, this PR aims to fix UNIX domain parsing by filtering "domains" such as `localhost` and `ip6-localhost` which are commonly found in `/etc/hosts`.
=> Improve UNIX domain parsing

dissect/target/plugins/apps/webserver/apache.py, tests/plugins/apps/webserver/test_apache.py, tests/plugins/apps/webserver/test_citrix.py
This PR improves the Apache access log parser. The `RE_ACCESS_COMMON_PATTERN` now supports empty `method`, `uri` and `protocol` values (e.g. `"-"`). Empty Apache values (`-`) are now cast to `None` as well. For context see the modified and added tests.
=> Improve Apache log format detection

dissect/target/tools/info.py
This PR adds the `--children` argument to `target-info`.
=> Add children argument to target-info tool

dissect/target/tools/shell.py, tests/tools/test_shell.py
Should fix #1111. Only tested locally on uv cpython 3.12 and 3.13 so far, curious to see if the regular CI test environments still pass.
=> Add workaround for ANSI codes target-shell tests

dissect/target/filesystems/exfat.py
The exFAT implementation still doesn't actually work but at least we can merge https://github.com/fox-it/dissect.util/pull/71 to clean up `dissect.util`.
=> Remove UTC class usage in exFAT code

dissect/target/filesystems/nfs.py, tests/filesystems/test_nfs.py
This is to avoid an nfs lookup error when you try to enter a target over
an nfs3 connection. Loaders attempt to check for files inside this path,
where it tries to do a dir lookup on a file and it crashes.
=> Raise a NotADirectoryError inside the NFSFilesystemEntry.get when it is a file

dissect/target/plugins/apps/container/docker.py, tests/plugins/apps/container/test_docker.py
`get_data_path` can return `None` in case the directory is not configured.
https://docs.docker.com/engine/daemon/#daemon-data-directory
=> Fix default Docker daemon data directories

dissect/target/filesystems/config.py, dissect/target/helpers/configutil.py, dissect/target/plugins/os/unix/linux/network.py, tests/_data/plugins/os/unix/linux/systemd.network/20-wired-static.network, tests/_data/plugins/os/unix/linux/systemd.network/30-wired-static-complex.network.d/10-override.conf, tests/_data/plugins/os/unix/linux/systemd.network/30-wired-static-complex.network.d/20-override.conf, tests/filesystems/test_config.py, tests/helpers/test_configutil.py, tests/plugins/os/unix/linux/test_network.py
Fixes:
-  `_select_parser` could be invoked with a `Path`, while it expects a `FileSystemEntry`. Additionally, there were multiple code paths in `parse` and `parse_config` to support `TargetPath`, `Path`, and `File` objects. Removed the dependence on `FileSystemEntry` by converting entries to `TargetPath` in the config file system.
- Systemd network parser did not collapse singleton values
- When multiple sections with the same name are encountered, the resulting key is a list of those sections:
Example:
```
key value1
key2 value2a
key value1
key2 value2b
key3 value3b
```
now parses as  `{"key value1": [{"key2": "value2a"}, {"key2": "value2b", "key3": "value3b"}]}`. Previously, this parsed as `{"key value1": {"key2": ["value2a", "value2b"], "key3": "value3b"}}`, where the parallel lists …
=> Support systemd drop files

dissect/target/plugins/os/windows/cam.py, tests/plugins/os/windows/test_cam.py
PR to fix the issue: 
https://github.com/fox-it/dissect.target/issues/1156
Resolved by identifying the parent of the 'device'-key to work around this problem.
=> cam.registry assumed wrong part of path as device

dissect/target/filesystems/config.py, dissect/target/helpers/mount.py, dissect/target/plugins/os/windows/tasks/job.py
Although there were multiple factors contributing to the high memory usage of target.mount, the cache size was a bit too generous. 
Significantly lowered the cache size
=> Lower target mount cache

dissect/target/plugins/os/unix/linux/network_managers.py
This PR makes sure the `parse_unix_dhcp_log_messages` function does not iterate endlessly when parsing `syslog` / `messages` records. Fixes #1172.
=> Limit `parse_unix_dhcp_log_messages` in parsed syslog messages

tests/loaders/test_acquire.py
This PR adds the benchmark test for Acquire tar files, as included in #935. This allows us to compare the performance of #935 by first merging this PR.
=> Add benchmark test for acquire tar

dissect/target/plugin.py, dissect/target/plugins/general/users.py, dissect/target/plugins/os/default/_os.py, dissect/target/plugins/os/unix/_os.py, dissect/target/plugins/os/unix/bsd/darwin/_os.py, dissect/target/plugins/os/windows/_os.py, tests/conftest.py, tests/plugins/general/test_users.py, tests/plugins/os/windows/test__os.py
- Ensure `%windir%/SysWOW64/config/systemprofile` is acquired and discoverable by plugins.
- Move `misc_home_dirs` into target.
- Added a new function `all_home_dirs` to discover user directories without requiring user information
=> Search additional paths for home directories

dissect/target/filesystems/cb.py, dissect/target/filesystems/smb.py, dissect/target/loaders/cb.py, dissect/target/loaders/mqtt.py, dissect/target/loaders/smb.py, tests/filesystems/test_cb.py, tests/filesystems/test_smb.py, tests/loaders/test_cb.py, tests/loaders/test_smb.py
This PR removes debug stacktraces from `target-* -vv` stderr output  from Carbon Black, SMB and MQTT loaders and filesystems. This change will cause several mocks to fail in the tests, unsure how we should fix those.
=> Check for optional dependencies

dissect/target/plugin.py, dissect/target/tools/utils.py, tests/conftest.py, tests/plugins/os/windows/test_cim.py, tests/test_plugin.py, tests/tools/test_query.py
This PR fixes a (slightly different) regression of https://github.com/fox-it/dissect.target/issues/421.
Since the plugin internals refactor #889 only `__regular__` plugins are returned when invoking `find_functions` (-> `_generate_long_paths`). Previously `OSPlugin` specific functions were also returned.
See the added test for steps how to reproduce using `target-query -l "*" <target>`.
=> Include OSPlugin functions in `find_functions` output

dissect/target/filesystems/zip.py, tests/filesystems/test_zip.py
Some issues are still present after #1270. This PR complete to make ZipLoader more robust
Example 1
```
datetime(1980,0,1,0,0,0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-533ec990f051> in <module>
----> 1 datetime(1980,0,1,0,0,0)
ValueError: month must be in 1..12
```
Example 2
```
datetime(1980,1,0,0,0,0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-dd5756bd5dae> in <module>
----> 1 datetime(1980,1,0,0,0,0)
ValueError: day is out of range for month
```
=> Fix incorrect timestamps of ZipInfo objects

dissect/target/target.py, dissect/target/tools/query.py, dissect/target/tools/shell.py, tests/test_target.py
This PR attempts to reduce non-informative stacktrace dumping by dissect when encountering invalid paths or broken loaders.
Before:
```
$ target-query -f users invalid.img
2025-09-08T09:25:25.982598Z [error    ] invalid.img: Provided target path does not exist [dissect.target.target]
Traceback (most recent call last):
File "/tmp/.venv/bin/target-query", line 10, in <module>
sys.exit(main())
~~~~^^
File "/tmp/dissect/target/tools/utils.py", line 394, in wrapper
return func(*args, **kwargs)
File "/tmp/dissect/target/tools/query.py", line 151, in main
for target in open_targets(args):
~~~~~~~~~~~~^^^^^^
File "/tmp/dissect/target/tools/utils.py", line 184, in open_targets
for target in targets:
^^^^^^^
File "/tmp/dissect/target/target.py", line 435, in open_all
for entry in path.iterdir(): …
```
=> Better error handling for invalid paths and broken loaders

dissect/target/plugins/filesystem/yara.py, tests/tools/test_yara.py
This PR adds a timestamp to the Yara plugin, by using the modification timestamp of the file. By adding this we can show yara results in a timeline method, allowing for easier analysis.
If there is any feedback please let me know!
=> Add timestamp to yara plugin

dissect/target/plugins/filesystem/ntfs/utils.py, dissect/target/plugins/os/windows/_os.py, dissect/target/volumes/disk.py, pyproject.toml, tests/plugins/filesystem/ntfs/test_mft.py
By converting an NTFS volume's serial number (from $boot) to a UUID, you can obtain a UUID even when utilizing the **Master Boot Record (MBR)**. Although the resulting identifier is less unique than a native GUID Partition Table (GPT) UUID, it remains sufficiently unique for the majority of practical applications and use cases.
=> Used volume SERIAL as UUID when it didnt exist

dissect/target/plugins/os/default/network.py, dissect/target/plugins/os/unix/linux/network.py, tests/plugins/os/unix/linux/test_network.py
- Make parsing of syslog optional in network rewrite.
- Limit number of messages parsed.
=> Make syslog parsing optional
