setup.py

Bump the version of flow.record to 3.5

---

setup.cfg

Update setup.cfg with a description field

---

dissect/target/plugins/os/windows/regf/trusteddocs.py
tests/test_plugins_os_windows_regf_trusteddocs.py

Fix obtaining user for each key and typehinting

---

dissect/target/container.py
tests/test_container_open.py

Fallback container detection to fh if path fails

---

dissect/target/loaders/remote.py
tests/test_loaders_remote.py

Add option to RemoteLoader to use custom CA.
(DIS-1517)

Add option to RemoteLoader to use custom CA

---

dissect/target/plugins/os/unix/linux/esxi/_os.py

Fix ESXi hostname and domain if not configured

---

dissect/target/loaders/remote.py
tests/test_loaders_remote.py

Allow the Remote Loader to use embedded SSL artefacts if available
(DIS-1518)

Allow remote loader to use embedded certificates (DIS-1518)

---

dissect/target/container.py

Remove duplicate registration of vmdk and ewf

---

dissect/target/filesystems/ffs.py

Fix birthtime for FFS1 filesystems

---

dissect/target/target.py

Move stacktrace from warning message to debug

---

dissect/target/filesystem.py
tests/test_filesystem.py
tests/test_plugins_apps_remoteaccess_teamviewer.py
tests/test_target_fs.py

Note for reviewers: review each commit on its own, they are intended to go un-squashed on the main branch.
(DIS-1632)

Refactor filesystem code

---

dissect/target/plugins/os/windows/regf/shimcache.py
tests/test_plugins_os_windows_shimcache.py

Add index of Shimcache entry to ShimcacheRecord

---

dissect/target/plugins/os/windows/defender.py

Improve Defender records

---

dissect/target/plugins/browsers/browser.py
dissect/target/plugins/browsers/chrome.py
dissect/target/plugins/browsers/firefox.py
dissect/target/plugins/browsers/iexplore.py
tests/test_plugins_browsers.py

Return individual visits for browser history

---

dissect/target/plugins/os/windows/regf/muicache.py
tests/test_plugins_os_windows_muicache.py
tests/test_plugins_os_windows_regf_muicache.py

Add MUIcache plugin

---

setup.py

Update the version of flow.record to 3.7

---

dissect/target/loader.py
dissect/target/loaders/velociraptor.py
tests/test_loaders_velociraptor.py

Add Velociraptor loader

---

dissect/target/plugins/os/windows/tasks.py

(DIS-1758)
Fixes https://github.com/fox-it/dissect/issues/15

Make tasks plugin a bit more robust

---

dissect/target/plugins/filesystem/ntfs/mft.py
dissect/target/plugins/filesystem/ntfs/mft_timeline.py

Make mft and mft_timeline plugin a bit more robust

---

dissect/target/plugins/os/windows/_os.py
dissect/target/plugins/os/windows/generic.py
tests/test_plugins_os_windows__os.py

Starting from NT 10.0 the registry keys used to indicate the NT version changed.
(DIS-1379)

Update the Windows version and ntversion plugins

---

dissect/target/helpers/network_managers.py
dissect/target/loaders/res.py

Use defusedxml instead of the build in xml module

---

dissect/target/plugin.py
dissect/target/tools/utils.py
tests/test_plugin.py
tests/test_registration.py

Use only .py files when loading plugins

---

dissect/target/plugins/os/windows/iis.py
tests/test_plugins_os_windows_iis.py

Make IIS parser more robust

---

dissect/target/tools/fs.py

Improve target-fs command line error handling

---

dissect/target/filesystems/zip.py
tests/test_filesystems_zip.py

Small fixes to zip filesystem

---

dissect/target/filesystem.py
dissect/target/helpers/fsutil.py
tests/test_target_path.py

Fix incorrect MappedFile behavior

---

dissect/target/plugins/browsers/iexplore.py

Improve the robustness of the InternetExplorerPlugin

---

dissect/target/helpers/record.py
dissect/target/plugins/child/hyper-v.py
dissect/target/plugins/child/virtuozzo.py
dissect/target/plugins/child/vmware_workstation.py
dissect/target/plugins/child/wsl.py
dissect/target/plugins/os/unix/linux/esxi/_os.py
tests/test_plugins_child_virtuozzo.py
tests/test_plugins_child_wsl.py

Change path type of ChildTargetRecord

---

dissect/target/tools/query.py

Change execution report log to debug

---

dissect/target/filesystem.py
dissect/target/filesystems/ad1.py
dissect/target/filesystems/cb.py
dissect/target/filesystems/dir.py
dissect/target/filesystems/exfat.py
dissect/target/filesystems/fat.py
dissect/target/filesystems/ffs.py
dissect/target/filesystems/itunes.py
dissect/target/filesystems/ntfs.py
dissect/target/filesystems/tar.py
dissect/target/filesystems/vmfs.py
dissect/target/filesystems/xfs.py
dissect/target/filesystems/zip.py

Correctly set volume in filesystems

---

setup.py

Update the flow.record dependency to 3.9

---

dissect/target/filesystems/tar.py
dissect/target/filesystems/zip.py
tests/test_filesystems_tar.py
tests/test_filesystems_zip.py

Fix TarFilesystem regression for relative lookups

---

dissect/target/filesystem.py
dissect/target/filesystems/ad1.py
dissect/target/filesystems/cb.py
dissect/target/filesystems/dir.py
dissect/target/filesystems/exfat.py
dissect/target/filesystems/extfs.py
dissect/target/filesystems/fat.py
dissect/target/filesystems/ffs.py
dissect/target/filesystems/itunes.py
dissect/target/filesystems/ntfs.py
dissect/target/filesystems/tar.py
dissect/target/filesystems/vmfs.py
dissect/target/filesystems/xfs.py
dissect/target/filesystems/zip.py

Clean up filesystem detection and add type hints

---

dissect/target/volume.py
dissect/target/volumes/bde.py
dissect/target/volumes/disk.py
dissect/target/volumes/lvm.py
dissect/target/volumes/vmfs.py

Clean up volume system detection

---

dissect/target/loaders/target.py

Change LoaderError to ImportError in target loader

---

dissect/target/filesystems/itunes.py
dissect/target/loaders/itunes.py

Improve support for iTunes backup files

---

dissect/target/helpers/network_managers.py

Fix XML parsing for the wicked networkmanager

---

dissect/target/filesystem.py

Fix RootFilesystemEntry's lattr()

---

dissect/target/tools/shell.py
tests/test_tools_shell.py

Print errors in target-shell when running with -q

---

dissect/target/helpers/fsutil.py
tests/test_helpers_fsutil.py

Make fsutil.open_decompress file extension agnostic

---

dissect/target/helpers/fsutil.py

Make importing and usage of the bz2 module conditional

---

dissect/target/filesystem.py
tests/test_filesystem.py

Add test cases for case(in)sensitivity of the VirtualFilesystem

---

dissect/target/helpers/network_managers.py
tests/test_plugins_os_unix_ips.py

This PR improves Unix DHCP IP address parsing.

Improve Unix DHCP IP parsing

---

dissect/target/plugins/os/windows/lnk.py

(DIS-1957)
Fixes issues when merging https://github.com/fox-it/dissect.shellitem/pull/18

Change Lnk(entry) to file-handle

---

dissect/target/loaders/targetd.py

Close targetd connection after use

Close targetd connection after use

---

dissect/target/plugins/os/windows/registry.py
tests/test_plugins_os_windows_registry.py

(DIS-1973)
Only doubt I have is if this should log to warning or debug.

Skip empty registry hives

---

dissect/target/plugins/os/unix/services.py
tests/test_plugins_os_unix_services.py

This PR fixes unix services parsing when encountering broken symlinks.

Fix services plugin for broken symlinks

---

dissect/target/helpers/mount.py
dissect/target/tools/mount.py

Mount all filesystems in target-mount

---

dissect/target/loaders/targetd.py

Targetd windows controller

---

dissect/target/plugins/general/users.py
tests/test_plugins_general_users.py

Fix user_details.find() to return users with uid 0

---

dissect/target/plugins/os/unix/history.py
dissect/target/plugins/os/unix/log/atop.py
dissect/target/plugins/os/unix/log/auth.py
dissect/target/plugins/os/unix/log/messages.py
tests/test_plugins_os_unix_log.py

Remove workarounds to map TargetPaths on path record fields

---

dissect/target/filesystem.py
dissect/target/filesystems/dir.py
dissect/target/helpers/fsutil.py
tests/conftest.py
tests/test_filesystem.py
tests/test_filesystems_dir.py
tests/test_helpers_fsutil.py

Implement attr()/lattr() in MappedFile and DirectoryFilesystemEntry

---

dissect/target/loaders/phobos.py
tests/test_loaders_phobos.py

Update the Phobos loader to use the new NTFS API

---

dissect/target/loaders/targetd.py

Add ssl support to targetd loader

---

dissect/target/loaders/log.py
dissect/target/plugins/apps/webservers/iis.py
tests/test_loaders_log.py

Add IIS logs to LogLoader

---

dissect/target/exceptions.py
dissect/target/loaders/targetd.py
dissect/target/tools/query.py

Allow multiple plugins at once for targetd-loader

---

dissect/target/plugins/os/unix/_os.py

Fix mounting ext filesystems for Unix targets

---

dissect/target/plugins/os/windows/sam.py

Fix the use of deprecated registry.iterkeys()

---

dissect/target/plugins/os/windows/log/evt.py

Change exception

---

dissect/target/plugins/os/windows/datetime.py
tests/conftest.py
tests/test_plugins_os_windows_datetime.py

Fix target-info time zone issue

---

dissect/target/tools/shell.py

Add fallback LS_COLORS scheme to target-shell

---

dissect/target/loaders/dir.py

Fix Dirloader to work with acquired dirs (-ot)

---

dissect/target/plugins/os/windows/task_helpers/tasks_xml.py
dissect/target/plugins/os/windows/tasks.py
tests/test_plugins_os_windows_tasks.py

Support multipe tasks per XML file

---

dissect/target/loaders/targetd.py

Improve empty response handling targetd

---

dissect/target/helpers/regutil.py
dissect/target/loaders/cb.py
dissect/target/loaders/res.py
dissect/target/plugins/os/windows/regf/appxdebugkeys.py
dissect/target/plugins/os/windows/registry.py
tests/conftest.py
tests/test_helpers_regutil.py
tests/test_plugins_os_windows_mru.py
tests/test_plugins_os_windows_regf_appxdebugkeys.py
tests/test_plugins_os_windows_registry.py

It is probably easiest to review the commits one by one instead of the whole thing.
The intent is also to not squash these 3 commits.

Add a globbing function to the registry plugin

---

dissect/target/plugins/general/users.py
dissect/target/plugins/os/windows/_os.py
dissect/target/plugins/os/windows/env.py
dissect/target/plugins/os/windows/registry.py

Clarify the relation between users and user hives

---

dissect/target/tools/mount.py

Fixes https://github.com/fox-it/dissect.target/issues/318

Disable threads in target-mount

---

dissect/target/plugin.py
tests/conftest.py
tests/test_plugin.py

Allow Default/None-OS to access plugins

---

dissect/target/tools/shell.py
tests/test_tools_shell.py

Fix duplicate files upon saving dirs in target-shell

---

dissect/target/plugins/apps/remoteaccess/anydesk.py

(DIS-1333)
This adds some more possible file locations for relevant AnyDesk trace files. Also contains the default locations for the AnyDesk client/service on Linux/MacOS.

Add additional AnyDesk paths

---

dissect/target/plugins/os/unix/bsd/ios/_os.py

Fix incorrect record annotation iOS

---

dissect/target/loaders/local.py
tests/test_loaders_local.py

Mount volatile Linux directories when running on a local target

---

dissect/target/plugins/apps/vpns/wireguard.py

Make the wireguard plugin more robust against missing data

---

dissect/target/plugins/os/windows/datetime.py

Fix vermin issues with calendar.SUNDAY not in Py3.9

---

dissect/target/helpers/xz.py
dissect/target/plugin.py
dissect/target/plugins/os/unix/_os.py
dissect/target/plugins/os/unix/generic.py
dissect/target/plugins/os/unix/linux/fortios/_os.py
dissect/target/plugins/os/unix/linux/fortios/generic.py
dissect/target/plugins/os/unix/linux/fortios/locale.py
tests/plugins/os/unix/log/test_messages.py
tests/test_plugin.py

This PR improves support for FortiOS versions `4.x`, `5,x`, `6.x` and `7.x`.

Improve FortiOS plugin

---

dissect/target/plugin.py

Amend documentation for `none` plugin export type

---

dissect/target/containers/fortifw.py
tests/containers/test_fortifw.py

Fix gzip trailer_offset calculation in FortiFirmwareFile

---

dissect/target/plugins/os/windows/defender.py
dissect/target/plugins/os/windows/defender_helpers/defender_patterns.py
dissect/target/plugins/os/windows/defender_helpers/defender_records.py
tests/_data/plugins/os/windows/defender/mplog/bmtelemetry.log
tests/_data/plugins/os/windows/defender/mplog/lines.log
tests/_data/plugins/os/windows/defender/mplog/resourcescan.log
tests/_data/plugins/os/windows/defender/mplog/rtp.log
tests/_data/plugins/os/windows/defender/mplog/threatactions.log
tests/plugins/os/windows/test_defender.py

Add MPLog parser to Defender plugin

---

dissect/target/helpers/cyber.py

Fix visual bugs in cyber

---

dissect/target/plugins/os/windows/defender.py

Improve type hint in Defender plugin

---

dissect/target/helpers/configutil.py
tests/helpers/test_configutil.py

Add CSV-ish config parser

---

dissect/target/loaders/utm.py

Fix UTM loader to skip non-disks

---

dissect/target/plugins/os/unix/_os.py

Add support for mounting by XFS label

---

dissect/target/plugins/filesystem/ntfs/mft.py
tests/plugins/filesystem/ntfs/test_mft.py

Add MACB aggregator to MFT

---

dissect/target/plugins/filesystem/yara.py

This PR fixes `--max-size` functionality.

Cast custom --max-size to integer in yara plugin

---

dissect/target/filesystem.py
dissect/target/filesystems/itunes.py
dissect/target/filesystems/tar.py
dissect/target/helpers/fsutil.py
tests/test_filesystem.py

Fix relative symlinks within a mounted filesystem

---

dissect/target/plugins/os/unix/linux/_os.py
dissect/target/plugins/os/unix/linux/redhat/_os.py
dissect/target/plugins/os/unix/locale.py
tests/conftest.py

This PR adds some small locale fixes for RHEL targets.

Generic locale fixes for RHEL

---

dissect/target/plugins/os/windows/registry.py
tests/plugins/os/windows/test_registry.py

Fix registry for legacy Windows versions

---

dissect/target/plugins/os/unix/log/utmp.py
tests/plugins/os/unix/log/test_utmp.py

This PR adds support for `/var/run/utmp` files.

Improve Linux utmp plugin

---

dissect/target/filesystems/jffs.py

Fix default argument for following symlinks in JFFS

---

dissect/target/loaders/vma.py
dissect/target/loaders/xva.py
pyproject.toml

Related to https://github.com/fox-it/dissect.hypervisor/pull/46

Reflect move of XVA and VMA to dissect.archive

---

dissect/target/filesystems/fat.py

Add `st_blocks` and `st_blksize` to stat output for FAT

---

pyproject.toml

Bump the flow.record dependency to version 3.18

---

dissect/target/plugins/os/windows/lnk.py

This PR improves the exception handling for the windows lnk plugin.

Improve lnk plugin exception handling

---

dissect/target/tools/shell.py

Fix ANSI color prompt in target-shell

---

dissect/target/plugins/os/windows/prefetch.py
tests/plugins/os/windows/test_prefetch.py

Add Windows 11 Prefetch version

---

dissect/target/plugins/apps/productivity/msoffice.py
dissect/target/tools/utils.py

This PR fixes Sphinx warnings introduced in #616 and #763. We would appreciate a look at #964 to prevent these issues in the future.

Fix sphinx docs warnings

---

dissect/target/plugin.py
tests/test_plugin.py

Fix parent plugin namespaces

---

pyproject.toml

Bump the flow.record dependency to version 3.19

---

dissect/target/plugin.py
dissect/target/plugins/apps/productivity/sevenzip.py
dissect/target/plugins/general/plugins.py
dissect/target/plugins/os/default/network.py
tests/test_plugin.py

Also add an initial example function for finding functions by record field types.
Depends on #763

Add retrieval of runtime information to plugin descriptors

---

dissect/target/plugins/apps/webserver/apache.py
dissect/target/plugins/apps/webserver/webserver.py
tests/plugins/apps/webserver/test_apache.py

This PR adds the `apache.hosts`  function (in line with #1073) to the `ApachePlugin`.

Add Apache VirtualHost parsing

---

dissect/target/target.py
dissect/target/tools/shell.py

Add "reload" command to target-shell, which helps when running against a live target.

Target reload

---

dissect/target/plugins/child/virtualbox.py
tests/_data/plugins/child/virtualbox/VirtualBox.xml
tests/plugins/child/test_virtualbox.py

This PR adds child detection support for Oracle VirtualBox VMs.

Add Oracle VirtualBox child support

---

dissect/target/helpers/docs.py
dissect/target/tools/utils.py
tests/tools/test_utils.py

Allow namespaces to accept arguments

---

dissect/target/plugins/apps/productivity/msoffice.py
dissect/target/plugins/apps/webserver/iis.py
dissect/target/plugins/filesystem/resolver.py
dissect/target/plugins/general/users.py
dissect/target/plugins/os/windows/amcache.py
tests/_data/plugins/os/windows/amcache/PcaAppLaunchDic.txt
tests/_data/plugins/os/windows/amcache/pca/PcaAppLaunchDic.txt
tests/_data/plugins/os/windows/amcache/pca/PcaGeneralDb0.txt
tests/_data/plugins/os/windows/amcache/pca/PcaGeneralDb1.txt
tests/plugins/filesystem/test_resolver.py
tests/plugins/os/windows/log/test_amcache.py

Add parser for `PcaGeneralDb*.txt` files

---

dissect/target/plugins/child/colima.py
tests/plugins/child/test_colima.py

Colima is a container runtime for MacOS and Linux.
https://github.com/abiosoft/colima

Add Colima children plugin 

---

dissect/target/loaders/log.py
tests/loaders/test_log.py

Fix log loader deprecation message

---

dissect/target/plugins/os/windows/regf/runkeys.py

Fix processing empty commands in runkeys plugin

---

dissect/target/loaders/ab.py
tests/conftest.py
tests/helpers/test_keychain.py
tests/loaders/test_ab.py
tests/plugins/apps/browser/test_chrome.py
tests/plugins/os/windows/credential/test_credhist.py
tests/plugins/os/windows/dpapi/keyprovider/test_keychain.py
tests/plugins/os/windows/dpapi/test_dpapi.py

Make the guarded keychain always be used.

Autouse guarded keychain in tests

---

dissect/target/plugins/apps/remoteaccess/splashtop.py
tests/_data/plugins/apps/remoteaccess/splashtop/SPLog.txt
tests/plugins/apps/remoteaccess/test_splashtop.py

Add Splashtop plugin

---

dissect/target/filesystems/zip.py
tests/filesystems/test_zip.py

Fix incorrect timestamps of `ZipInfo` objects

---

dissect/target/plugins/os/windows/_os.py
dissect/target/plugins/os/windows/generic.py
tests/plugins/os/windows/test__os.py

Cross lookup windows user name from sam 

---

pyproject.toml

Similar to https://github.com/fox-it/flow.record/pull/189/files
Upcoming release we will still support 3.9 AFAIK

Pin zstandard and remove superfluous comment

---

dissect/target/plugins/filesystem/ntfs/usnjrnl.py
pyproject.toml

Due to https://github.com/fox-it/dissect.ntfs/pull/44.

Fix moved dissect.ntfs import
